### PR TITLE
Update readme to tick off file scoped types

### PR DESCRIPTION
**Pull request by tamasvajk**

### CODE REVIEW

**Comment by damieng** [comment]
Feel free to merge without review on readme's etc.

**Comment by tamasvajk** [comment]
> Feel free to merge without review on readme's etc.

I don't think I have the right to merge:
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by damieng** [comment]
Sorry, I thought you were on the semantic team at GitHub who have write access.

I've sent you a write-access invite to this repo.

**Comment by tamasvajk** [comment]
> Sorry, I thought you were on the semantic team at GitHub who have write access.
> 
> I've sent you a write-access invite to this repo.

Thanks. No, I'm in CodeQL.

**Pull request merged**
